### Check Gateway Deploy
GET https://klowhub-gateway-api-824410275969.southamerica-east1.run.app/gateway/hello
Content-Type: application/json

### Check Gateway Local
GET http://localhost:3000/gateway/hello
Content-Type: application/json