export const publicRoutes: string[] = [
  '/',
  '/auth/register',
  '/auth/login',
  '/auth/status',
  '/auth/verifyEmail',
  '/auth/resetToken',
  '/auth/test',
  '/auth/logout',
  '/courses/test',
  '/pubsub/test',
  "/signatures/signed-urls",
  '/courses/filter',
  '/courses/',
  '/courses/create',
  '/users',
  '/users/:id',
];