services:
  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      USERS_MICROSERVICE_HOST: ${USERS_MICROSERVICE_HOST}
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}
      MICROSERVICE_HOST: ${MICROSERVICE_HOST}
      MICROSERVICE_PORT: ${MICROSERVICE_PORT}
      COURSES_SERVICE_HOST: ${COURSES_SERVICE_HOST}
      COURSES_SERVICE_PORT: ${COURSES_SERVICE_PORT}
    volumes:
      - ./apps/gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - users
      - courses

  users:
    build:
      context: ./apps/users
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      MICROSERVICE_HOST: ${MICROSERVICE_HOST}
      MICROSERVICE_PORT: ${MICROSERVICE_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_UNPOOLED: ${DATABASE_URL_UNPOOLED}
      PGHOST: ${PGHOST}
      PGHOST_UNPOOLED: ${PGHOST_UNPOOLED}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_URL_NON_POOLING: ${POSTGRES_URL_NON_POOLING}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_URL_NO_SSL: ${POSTGRES_URL_NO_SSL}
    volumes:
      - ./apps/users:/usr/src/app
      - /usr/src/app/node_modules

  courses:
    build:
      context: ./apps/courses
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      MONGO_URI: ${MONGO_URI}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      USERS_MICROSERVICE_HOST: ${USERS_MICROSERVICE_HOST}
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}
      MICROSERVICE_HOST: ${MICROSERVICE_HOST}
      MICROSERVICE_PORT: ${MICROSERVICE_PORT}
      COURSES_SERVICE_HOST: ${COURSES_SERVICE_HOST}
      COURSES_SERVICE_PORT: ${COURSES_SERVICE_PORT}

    volumes:
      - ./apps/courses:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
