version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      SERVICE: gateway
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      USERS_MICROSERVICE_HOST: users
      USERS_MICROSERVICE_PORT: 3001
      COURSES_MICROSERVICE_HOST: courses
      COURSES_MICROSERVICE_PORT: 3002
      UPLOAD_MICROSERVICE_HOST: upload
      UPLOAD_SERVICE_PORT: ${UPLOAD_SERVICE_PORT}
    volumes:
      - ./apps/gateway:/usr/src/app/apps/gateway
    depends_on:
      - users
      - courses
    networks:
      - app-network

  users:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      SERVICE: users
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      USERS_MICROSERVICE_HOST: users
      USERS_MICROSERVICE_PORT: 3001
      FRONTEND_URL: ${FRONTEND_URL}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      GOOGLE_CLIENT_ID : ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET : ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL : ${GOOGLE_CALLBACK_URL}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - ./apps/users:/usr/src/app/apps/users
    networks:
      - app-network

  courses:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      SERVICE: courses
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      COURSES_MICROSERVICE_HOST: courses
      COURSES_MICROSERVICE_PORT: 3002
    volumes:
      - ./apps/courses:/usr/src/app/apps/courses
    depends_on:
      - users
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
