apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: courses-hpa
  namespace: courseservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: courses-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80