apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-deployment
  namespace: courseservice
  labels:
    app: klowhub-courses-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: klowhub-courses-api
  template:
    metadata:
      labels:
        app: klowhub-courses-api
    spec:
      containers:
        - name: klowhub-courses-api
          image: gcr.io/${GCP_PROJECT_ID}/klowhub-courses-api:${IMAGE_TAG}
          ports:
            - containerPort: 3002  # Puerto en el que la app está escuchando dentro del contenedor
          env:
            - name: NODE_ENV
              value: "production"
            - name: COURSES_SERVICE_HOST
              value: "3002"
            - name: COURSES_SERVICE_PORT
              value: "0.0.0.0"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"  
            - name: MONGO_URI
              value: "${MONGO_URI}"  
