apiVersion: v1
kind: Service
metadata:
  name: courses-service
  namespace: courseservice
spec:
  selector:
    app: klowhub-courses-api
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
