apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: gateway 
spec:
  type: LoadBalancer 
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
