apiVersion: apps/v1
kind: Deployment
metadata:
  name: klowhub-upload-api-deployment
  namespace: gcc-upload
  labels:
    app: klowhub-upload-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: klowhub-upload-api
  template:
    metadata:
      labels:
        app: klowhub-upload-api
    spec:
      containers:
      - name: klowhub-upload-api
        image: ${GCLOUD_REGION}-docker.pkg.dev/${GCLOUD_PROJECT_ID}/klowhub-server/${UPLOAD_SERVICE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: UPLOAD_SERVICE_PORT
          value: "3003"
        - name: UPLOAD_MICROSERVICE_HOST
          value: "0.0.0.0"
        - name: PROJECT_ID
          value: "${GCLOUD_PROJECT_ID}"
        - name: BUCKET_NAME
          value: "${BUCKET_NAME}"
