apiVersion: v1
kind: Service
metadata:
  name: klowhub-upload-api-service
  namespace: gcc-upload
spec:
  selector:
    app: klowhub-upload-api
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
